### ISSUE TITLE
[PE-D] Cannot add 2 internships from the same company.

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#146]
A user may have 2 applications to the same company for different positions, such as Software Engineer and QA Engineer. However, InternApply only allows 1 application per company.

Use case:

1. `add n/Shopee j/Software Engineer Intern p/87438807 e/hr@shopee.sg a/5 Science Park Dr, #06-40 ast/APPLIED`
2. `add n/Shopee j/QA Engineer Intern p/87438807 e/hr@shopee.sg a/5 Science Park Dr, #06-40 ast/APPLIED`

Output: `This application already exists in InternApply.`

![image.png](https://raw.githubusercontent.com/TypeDefinition/ped/main/files/2da4d3df-e64f-499b-a7a8-2987e0e55073.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TypeDefinition/ped#1

**Comment by lchokhoe** [comment]
"Good to fix" Bug.

Edit
Possible solution is to modify Application#isSameApplication() method. Currently uses the Application's Name as a determining factor.

Define "Duplicate Application". Suggested definition: Applications that have the same Name, Job Title, Phone, Address, Email and Optional Tags (FlexyTags) are considered duplicates.

FAQ:
I have an existing application to a company that I applied to where I got rejected and I am trying to reapply to the same company with the exact same details. Since SIA cannot have duplicate applications, what should I do?
Option 1: Using `edit`, you can simply reuse the existing application with updated information.

Option 2: If you are looking to keep the existing application and it's information untouched, then we suggest including an additional "t/NthAttempt" to differentiate your new application and the existing application. This will not violate our duplication clause while also allowing you to keep information on your existing application.

Related to issue #150
